"""add virustotal scan fields

Revision ID: 412d30bf68c9
Revises: fde3181ea109
Create Date: 2026-09-10 11:10:36.768042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412d30bf68c9'
down_revision: Union[str, Sequence[str], None] = 'fde3181ea109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "scans",
        sa.Column(
            "vt_found",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_malicious",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_suspicious",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_harmless",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_undetected",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_reputation",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "vt_last_analysis_date",
            sa.BigInteger(),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'vt_last_analysis_date')
    op.drop_column('scans', 'vt_reputation')
    op.drop_column('scans', 'vt_undetected')
    op.drop_column('scans', 'vt_harmless')
    op.drop_column('scans', 'vt_suspicious')
    op.drop_column('scans', 'vt_malicious')
    op.drop_column('scans', 'vt_found')
    # ### end Alembic commands ###
