"""add scan analysis fields

Revision ID: fde3181ea109
Revises: 4f6e5f398c96
Create Date: 2026-09-09 10:50:58.210031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde3181ea109'
down_revision: Union[str, Sequence[str], None] = '4f6e5f398c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        "scans",
        sa.Column(
            "is_malicious",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "matched_rule",
            sa.String(length=100),
            nullable=True,
        ),
    )

    op.add_column(
        "scans",
        sa.Column(
            "scan_status",
            sa.String(length=20),
            nullable=False,
            server_default="PENDING",
        ),
    )

    # Remove defaults so future inserts must explicitly set them
    op.alter_column("scans", "is_malicious", server_default=None)
    op.alter_column("scans", "scan_status", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scans', 'scan_status')
    op.drop_column('scans', 'matched_rule')
    op.drop_column('scans', 'is_malicious')
    # ### end Alembic commands ###
